language: common-lisp
sudo: required

os:
  - linux
  - osx

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_BRANCH=release
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - WRK_VERSION=4.0.2
  matrix:
    - LISP=sbcl-bin

addons:
  apt:
    packages:
      - libev-dev

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libev; fi
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  # for thread-support on OS X
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ros install sbcl; fi

  # wrk, go for benchmarking
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      curl -L "https://github.com/wg/wrk/archive/$WRK_VERSION.tar.gz" | tar xzf -;
      (cd "wrk-$WRK_VERSION/" && make && cp wrk ~/.roswell/bin);
      sudo apt-get install golang;
    fi

  - ros install prove
  - ros install fukamachi/clack

before_script:
  - ros run -- --version

script:
  - run-prove woo-test.asd
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then benchmark/run-benchmark benchmark/woo/run; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then benchmark/run-benchmark benchmark/go/run; fi
